# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Release Tag"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 kafkabroker" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 schemaregistry" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=${{ github.event.inputs.tags }}" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/kafka-connect-json-record/kafka-connect-json-record/target/components/packages/barhatch-kafka-connect-json-record-${{ github.event.inputs.tags }}.zip
          asset_name: barhatch-kafka-connect-json-record-${{ github.event.inputs.tags }}.zip
          tag: ${{ github.event.inputs.tags }}
          overwrite: true
          body: "Created release"
